#!/bin/sh

# Home manager evironment
if [ -f "/etc/profiles/per-user" ]; then
  source /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh
elif [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
  source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
fi

# Nix environment
if [ -f "/etc/profile.d/nix.sh" ]; then
  source /etc/profile.d/nix.sh
elif [ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  source $HOME/.nix-profile/etc/profile.d/nix.sh
fi
