{
  imports = [
    ./appImage.nix
    ./audio.nix
    ./automount.nix
    ./base.nix
    ./command-not-found.nix
    ./dbus.nix
    ./diff.nix
    ./docs.nix
    ./fhs-compact.nix
    ./firmware.nix
    ./flatpak.nix
    ./fonts.nix
    ./libvirt.nix
    ./locale.nix
    ./logind.nix
    ./logs.nix
    ./oomd.nix
    ./power.nix
    ./printing.nix
    ./scheduler.nix
    ./secrets.nix
    ./touchpad.nix
    ./xdg-portals.nix
    ./xserver.nix
    ./yubikey.nix
  ];
}
