{
  imports = [
    ./apparmor.nix
    ./appImage.nix
    ./console.nix
    ./dbus.nix
    ./diff.nix
    ./fhs-compact.nix
    ./flatpak.nix
    ./gnupg.nix
    ./irqbalance.nix
    ./libvirt.nix
    ./locale.nix
    ./logind.nix
    ./logs.nix
    ./printing.nix
    ./serial.nix
    ./sudo.nix
  ];
}
